# Site settings
title: Conservation Genetics
description: Bringing Genomics to Naturalists
baseurl: "" # the subpath of your site, e.g., /blog
url: "http://ljdnielsen.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional settings
author: Lasse J.D. Nielsen
email: lassejdnielsen@gmail.com

# If you're using any plugins, list them here
plugins:
  - jekyll-feed
  # Add other plugins you are using